#!/usr/bin/env bash
# Run one small GEMM with tracing on and open it in GTKWave.
#
#   sim/wave.sh                          smallest case: 2x2 * 2x2 on a 2x2 array
#   sim/wave.sh -d 4x4x4                 one 4x4 tile
#   sim/wave.sh -d 8x4x4                 two activation tiles down a 4x4 array
#   sim/wave.sh -d 4x8x4 -q              two K tiles, requantized output
#   sim/wave.sh -v full                  same run, all 82 traces
#   sim/wave.sh -t test_bubble_path -n 4 a named regression test instead
#
#   -d MxKxN   GEMM dimensions (default 2x2x2). K and N must be multiples of
#              the array size; M need not be.
#   -n SIZE    array size. Default: K, so -d alone gives a single-tile GEMM.
#              Must be a power of two -- tile counts are computed as >>log2(N),
#              and gemm_ctrl asserts cfg_k[log2(N)-1:0]==0. N=3 cannot work.
#   -t TEST    run this test from test_gemm_top.py instead of the custom-dims
#              one; -d is then ignored.
#   -v VIEW    view: "control" (default, 41 traces) or "full" (82).
#              Generated by sim/waves/gen_gtkw.py into the build dir.
#   -q         enable requantization (WAVE_MULT / WAVE_SHIFT to tune).
#   Anything after -- is passed through to run.py (e.g. -- --seed 1).
set -euo pipefail

DIMS=2x2x2; SIZE=; TEST=; VIEW=control; QUANT=0
while getopts "d:n:t:v:qh" o; do
  case $o in
    d) DIMS=$OPTARG ;;
    n) SIZE=$OPTARG ;;
    t) TEST=$OPTARG ;;
    v) VIEW=$OPTARG ;;
    q) QUANT=1 ;;
    h) sed -n '2,20p' "$0"; exit 0 ;;
    *) exit 2 ;;
  esac
done
shift $((OPTIND - 1))
[ "${1:-}" = "--" ] && shift

ROOT=$(cd "$(dirname "$0")/.." && pwd)
PY=${PY:-$ROOT/.venv/bin/python}
case $VIEW in
  control|full) ;;
  *) echo "wave.sh: -v wants 'control' or 'full', got '$VIEW'" >&2; exit 2 ;;
esac

if [ -n "$TEST" ]; then
  SIZE=${SIZE:-4}
else
  IFS=x read -r M K NN <<<"$DIMS"
  [ -n "${NN:-}" ] || { echo "wave.sh: -d wants MxKxN, got '$DIMS'" >&2; exit 2; }
  SIZE=${SIZE:-$K}
  TEST=test_wave_custom
  export WAVE_DIMS=$DIMS WAVE_QUANT=$QUANT
fi

# Power-of-two check up front: otherwise this surfaces as an SVA firing several
# seconds into the run, which reads like an RTL bug rather than a bad argument.
case $SIZE in
  1|2|4|8|16|32|64) ;;
  *) echo "wave.sh: array size $SIZE is not a power of two" >&2; exit 2 ;;
esac

DUMP=$ROOT/sim/build/cocotb_n$SIZE/dump.vcd
rm -f "$DUMP"
"$PY" "$ROOT/tb/cocotb/run.py" -n "$SIZE" --testcase "$TEST" --waves "$@"

[ -f "$DUMP" ] || { echo "wave.sh: no dump at $DUMP" >&2; exit 1; }

# Verilator's cocotb harness emits an unnamed root scope, which would make every
# path in the save file start with a bare '.'. Name it TOP instead.
sed -i '0,/\$scope module  \$end/s/\$scope module  \$end/$scope module TOP $end/' "$DUMP"

# Generated per run: GTKWave binds a vector only when the trace name carries its
# full declared range, and those ranges move with the array size.
GTKW=$ROOT/sim/build/cocotb_n$SIZE/$VIEW.gtkw
"$PY" "$ROOT/sim/waves/gen_gtkw.py" "$DUMP" "$VIEW" "$GTKW"

echo "wave.sh: $(grep -c '^#' "$DUMP") timestamps, $(du -h "$DUMP" | cut -f1)"
exec gtkwave "$DUMP" "$GTKW"
